apiVersion: services.cloud.sap.com/v1
kind: ServiceInstance
metadata:
    name: SaaS Provisioning Service
    namespace: cdf-dev
spec:
    serviceOfferingName: saas-registry
    servicePlanName: application
    externalName: cdf-saas-provisioning