apiVersion: services.cloud.sap.com/v1alpha1
kind: ServiceInstance
metadata:
  name: btp-auditlog
  labels:
    cic.sap.com/managed-by: di-cs-meta
spec:
  serviceOfferingName: auditlog
  servicePlanName: oauth2